name: rhino_bond
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  flutter_staggered_grid_view: ^0.6.2
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  supabase: ^2.0.0
  provider: ^6.1.1
  supabase_flutter: ^2.0.0
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.7
  url_launcher: ^6.2.0
  flutter_carousel_widget: ^3.1.0
  permission_handler: ^10.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  intl_utils: ^2.8.8
flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.svg
  generate: true

l10n:
  arb-dir: lib/l10n
  output-dir: lib/l10n/generated
