const Map<String, String> en = {
  // General
  'appTitle': 'Rhino Bond',
  'welcome': 'Welcome',
  'welcomeBack': 'Welcome Back',
  'signInToContinue': 'Sign in to continue',
  'loading': 'Loading...',

  // Auth & Profile
  'login': 'Login',
  'register': 'Register',
  'phoneNumber': 'Phone Number',
  'email': 'Email',
  'password': 'Password',
  'currentPassword': 'Current Password',
  'newPassword': 'New Password',
  'confirmPassword': 'Confirm New Password',
  'fullName': 'Full Name',
  'address': 'Address',
  'pincode': 'Pincode',
  'state': 'State',
  'enterOtp': 'Enter OTP',
  'sendOtp': 'Send OTP',
  'verifyOtp': 'Verify OTP',
  'otpSentSuccessfully': 'OTP sent successfully!',
  'pleaseEnterPhoneNumber': 'Please enter your phone number',
  'pleaseEnterOtp': 'Please enter the OTP',
  'invalidOtp': 'Invalid OTP',
  'loginSuccessful': 'Login successful!',

  // Validation Messages
  'pleaseEnterName': 'Please enter your name',
  'pleaseEnterEmail': 'Please enter your email',
  'pleaseEnterValidEmail': 'Please enter a valid email',
  'pleaseEnterPhone': 'Please enter your phone number',
  'pleaseEnterPassword': 'Please enter your password',
  'pleaseEnterCurrentPassword': 'Please enter your current password',
  'pleaseEnterNewPassword': 'Please enter a new password',
  'pleaseConfirmPassword': 'Please confirm your new password',
  'passwordsDoNotMatch': 'Passwords do not match',
  'passwordMinLength': 'Password must be at least 6 characters long',
  'pincodeMustBe6Digits': 'Pincode must be 6 digits',
  'phoneMustBe10Digits': 'Phone number must be 10 digits',
  'pleaseEnterAddress': 'Please enter your address',
  'pleaseEnterPincode': 'Please enter your pincode',
  'pleaseEnterState': 'Please enter your state',

  // Settings
  'settings': 'Settings',
  'profileSettings': 'Profile Settings',
  'appSettings': 'App Settings',
  'security': 'Security',
  'changePassword': 'Change Password',
  'editProfile': 'Edit Profile',
  'darkMode': 'Dark Mode',
  'pushNotifications': 'Push Notifications',
  'notificationsSubtitle': 'Receive notifications about rewards and updates',
  'language': 'Language',
  'biometricAuth': 'Biometric Authentication',
  'biometricAuthSubtitle': 'Use fingerprint or face ID to login',
  'privacyPolicy': 'Privacy Policy',
  'termsOfService': 'Terms of Service',
  'about': 'About',
  'appVersion': 'App Version',
  'checkForUpdates': 'Check for Updates',
  'deleteAccount': 'Delete Account',
  'deleteAccountSubtitle': 'Permanently delete your account and all data',
  'cancel': 'Cancel',
  'delete': 'Delete',

  // Account
  'myAccount': 'My Account',
  'saveProfile': 'Save Profile',
  'saveChanges': 'Save Changes',
  'profileUpdated': 'Profile updated successfully',
  'passwordChanged': 'Password changed successfully',

  // Rewards
  'points': 'points',
  'pointsRequired': 'points required',
  'redeemNow': 'Redeem Now',
  'confirmRedemption': 'Confirm Redemption',
  'redeemConfirmMessage':
      'Are you sure you want to redeem {title} for {points} points?',
  'confirm': 'Confirm',
  'successfullyRedeemed': 'Successfully redeemed {title}!',

  // Error Messages
  'loginFailed': 'Login failed: {error}',
  'registrationFailed': 'Registration failed: {error}',
  'errorOccurred': 'Error: {error}',
  'fillAllFields': 'Please fill in all fields',

  // Missing keys
  'pleaseFillInAllFields': 'Please fill in all fields',
  'resendOtp': 'Resend OTP',
  'dontHaveAnAccount': "Don't have an account?",
};
