const Map<String, String> gu = {
  // General
  'appTitle': 'રાઇનો બોન્ડ',
  'welcome': 'સ્વાગત છે',
  'welcomeBack': 'પુનઃ સ્વાગત છે',
  'signInToContinue': 'ચાલુ રાખવા માટે સાઇન ઇન કરો',
  'loading': 'લોડ થઈ રહ્યું છે...',

  // Auth & Profile
  'login': 'લૉગિન',
  'register': 'નોંધણી કરો',
  'phoneNumber': 'ફોન નંબર',
  'email': 'ઈમેલ',
  'password': 'પાસવર્ડ',
  'currentPassword': 'વર્તમાન પાસવર્ડ',
  'newPassword': 'નવો પાસવર્ડ',
  'confirmPassword': 'નવો પાસવર્ડ કન્ફર્મ કરો',
  'fullName': 'પૂરું નામ',
  'address': 'સરનામું',
  'pincode': 'પિનકોડ',
  'state': 'રાજ્ય',
  'enterOtp': 'ઓટીપી દાખલ કરો',
  'sendOtp': 'ઓટીપી મોકલો',
  'verifyOtp': 'ઓટીપી ચેક કરો',
  'otpSentSuccessfully': 'ઓટીપી સફળતાપૂર્વક મોકલવામાં આવ્યો!',
  'pleaseEnterPhoneNumber': 'કૃપા કરી તમારો ફોન નંબર દાખલ કરો',
  'pleaseEnterOtp': 'કૃપા કરી ઓટીપી દાખલ કરો',
  'invalidOtp': 'અમાન્ય ઓટીપી',
  'loginSuccessful': 'લૉગિન સફળતાપૂર્વક થયું!',

  // Validation Messages
  'pleaseEnterName': 'કૃપા કરી તમારું નામ દાખલ કરો',
  'pleaseEnterEmail': 'કૃપા કરી તમારો ઈમેલ દાખલ કરો',
  'pleaseEnterValidEmail': 'કૃપા કરી માન્ય ઈમેલ દાખલ કરો',
  'pleaseEnterPhone': 'કૃપા કરી તમારો ફોન નંબર દાખલ કરો',
  'pleaseEnterPassword': 'કૃપા કરી તમારો પાસવર્ડ દાખલ કરો',
  'pleaseEnterCurrentPassword': 'કૃપા કરી તમારો વર્તમાન પાસવર્ડ દાખલ કરો',
  'pleaseEnterNewPassword': 'કૃપા કરી નવો પાસવર્ડ દાખલ કરો',
  'pleaseConfirmPassword': 'કૃપા કરી તમારો નવો પાસવર્ડ કન્ફર્મ કરો',
  'passwordsDoNotMatch': 'પાસવર્ડ મેળ ખાતા નથી',
  'passwordMinLength': 'પાસવર્ડ ઓછામાં ઓછા 6 અક્ષરનો હોવો જોઈએ',
  'pincodeMustBe6Digits': 'પિનકોડ 6 અંકનો હોવો જોઈએ',
  'phoneMustBe10Digits': 'ફોન નંબર 10 અંકનો હોવો જોઈએ',
  'pleaseEnterAddress': 'કૃપા કરી તમારું સરનામું દાખલ કરો',
  'pleaseEnterPincode': 'કૃપા કરી તમારો પિનકોડ દાખલ કરો',
  'pleaseEnterState': 'કૃપા કરી તમારો રાજ્ય દાખલ કરો',

  // Settings
  'settings': 'સેટિંગ્સ',
  'profileSettings': 'પ્રોફાઇલ સેટિંગ્સ',
  'appSettings': 'એપ સેટિંગ્સ',
  'security': 'સુરક્ષા',
  'changePassword': 'પાસવર્ડ બદલો',
  'editProfile': 'પ્રોફાઇલ સંપાદિત કરો',
  'darkMode': 'ડાર્ક મોડ',
  'pushNotifications': 'પુશ નોટિફિકેશન',
  'notificationsSubtitle': 'રિવોર્ડ્સ અને અપડેટ્સ વિશે નોટિફિકેશન મેળવો',
  'language': 'ભાષા',
  'biometricAuth': 'બાયોમેટ્રિક પ્રਮાણીકરણ',
  'biometricAuthSubtitle': 'લૉગિન માટે ફિંગરਪ્રિંટ અથવા ફેસ આઈડી વાપરો',
  'privacyPolicy': 'ગોપનીયતા નીતੀ',
  'termsOfService': 'સેવાની શરતો',
  'about': 'વિશે',
  'appVersion': 'એપ્લિકેશન વર્ઝન',
  'checkForUpdates': 'અપડેટ્સ તપાસો',
  'deleteAccount': 'એકાઉન્ટ કાઢી નાખો',
  'deleteAccountSubtitle': 'તમારું એકાઉન્ટ અને બધો ડેટા કાયમી રીતે કાઢી નાખો',
  'cancel': 'રદ્દ કરો',
  'delete': 'કાઢી નાખો',

  // Account
  'myAccount': 'મારું એકાઉન્ટ',
  'saveProfile': 'પ્રોફાઇલ સાચવો',
  'saveChanges': 'ફેરફારો સાચવો',
  'profileUpdated': 'પ્રોફાઇલ સફળતાપૂર્વક અપડેટ થયું',
  'passwordChanged': 'પાસવર્ડ સફળતાપૂર્વક બદલાયો',

  // Rewards
  'points': 'પોઈન્ટ્સ',
  'pointsRequired': 'પોઈન્ટ્સ જરૂરી',
  'redeemNow': 'હવે રિડીમ કરો',
  'confirmRedemption': 'રિડેમ્પશનની પુષ્ટિ કરો',
  'redeemConfirmMessage':
      'શું તમે ખરેખર {points} પોઈન્ટ્સ માટે {title} રિડીમ કરવા માંગો છો?',
  'confirm': 'પુષ્ટિ કરો',
  'successfullyRedeemed': '{title} સફળતાપૂર્વક રિડીમ થયું!',

  // Error Messages
  'loginFailed': 'લૉગિન નિષ્ફળ: {error}',
  'registrationFailed': 'નોંધણી નિષ્ફળ: {error}',
  'errorOccurred': 'ભૂલ: {error}',
  'fillAllFields': 'કૃપા કરી બધા ક્ષેત્રો ભરો',
};
