const Map<String, String> hi = {
  // General
  'appTitle': 'राइनो बॉन्ड',
  'welcome': 'स्वागत है',
  'welcomeBack': 'पुनः स्वागत है',
  'signInToContinue': 'जारी रखने के लिए साइन इन करें',
  'loading': 'लोड हो रहा है...',

  // Auth & Profile
  'login': 'लॉगिन',
  'register': 'पंजीकरण',
  'phoneNumber': 'फोन नंबर',
  'email': 'ईमेल',
  'password': 'पासवर्ड',
  'currentPassword': 'वर्तमान पासवर्ड',
  'newPassword': 'नया पासवर्ड',
  'confirmPassword': 'नया पासवर्ड पुष्टि करें',
  'fullName': 'पूरा नाम',
  'address': 'पता',
  'pincode': 'पिनकोड',
  'state': 'राज्य',
  'enterOtp': 'ओटीपी दर्ज करें',
  'sendOtp': 'ओटीपी भेजें',
  'verifyOtp': 'ओटीपी सत्यापित करें',
  'otpSentSuccessfully': 'ओटीपी सफलतापूर्वक भेजा गया!',
  'pleaseEnterPhoneNumber': 'कृपया अपना फोन नंबर दर्ज करें',
  'pleaseEnterOtp': 'कृपया ओटीपी दर्ज करें',
  'invalidOtp': 'अमान्य ओटीपी',
  'loginSuccessful': 'लॉगिन सफलतापूर्वक हुआ!',

  // Validation Messages
  'pleaseEnterName': 'कृपया अपना नाम दर्ज करें',
  'pleaseEnterEmail': 'कृपया अपना ईमेल दर्ज करें',
  'pleaseEnterValidEmail': 'कृपया मान्य ईमेल दर्ज करें',
  'pleaseEnterPhone': 'कृपया अपना फोन नंबर दर्ज करें',
  'pleaseEnterPassword': 'कृपया अपना पासवर्ड दर्ज करें',
  'pleaseEnterCurrentPassword': 'कृपया अपना वर्तमान पासवर्ड दर्ज करें',
  'pleaseEnterNewPassword': 'कृपया नया पासवर्ड दर्ज करें',
  'pleaseConfirmPassword': 'कृपया अपने नए पासवर्ड की पुष्टि करें',
  'passwordsDoNotMatch': 'पासवर्ड मेल नहीं खाते',
  'passwordMinLength': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए',
  'pincodeMustBe6Digits': 'पिनकोड 6 अंकों का होना चाहिए',
  'phoneMustBe10Digits': 'फोन नंबर 10 अंकों का होना चाहिए',
  'pleaseEnterAddress': 'कृपया अपना पता दर्ज करें',
  'pleaseEnterPincode': 'कृपया अपना पिनकोड दर्ज करें',
  'pleaseEnterState': 'कृपया अपना राज्य दर्ज करें',

  // Settings
  'settings': 'सेटिंग्स',
  'profileSettings': 'प्रोफाइल सेटिंग्स',
  'appSettings': 'ऐप सेटिंग्स',
  'security': 'सुरक्षा',
  'changePassword': 'पासवर्ड बदलें',
  'editProfile': 'प्रोफाइल संपादित करें',
  'darkMode': 'डार्क मोड',
  'pushNotifications': 'पुश नोटिफिकेशन',
  'notificationsSubtitle':
      'रिवॉर्ड्स और अपडेट्स के बारे में नोटिफिकेशन प्राप्त करें',
  'language': 'भाषा',
  'biometricAuth': 'बायोमेट्रिक प्रमाणीकरण',
  'biometricAuthSubtitle': 'लॉगिन के लिए फिंगरप्रिंट या फेस आईडी का उपयोग करें',
  'privacyPolicy': 'गोपनीयता नीति',
  'termsOfService': 'सेवा की शर्तें',
  'about': 'के बारे में',
  'appVersion': 'ऐप वर्जन',
  'checkForUpdates': 'अपडेट के लिए जाँच करें',
  'deleteAccount': 'खाता हटाएं',
  'deleteAccountSubtitle': 'अपना खाता और सभी डेटा स्थायी रूप से हटाएं',
  'cancel': 'रद्द करें',
  'delete': 'हटाएं',

  // Account
  'myAccount': 'मेरा खाता',
  'saveProfile': 'प्रोफाइल सहेजें',
  'saveChanges': 'परिवर्तन सहेजें',
  'profileUpdated': 'प्रोफाइल सफलतापूर्वक अपडेट किया गया',
  'passwordChanged': 'पासवर्ड सफलतापूर्वक बदल दिया गया',

  // Rewards
  'points': 'पॉइंट्स',
  'pointsRequired': 'आवश्यक पॉइंट्स',
  'redeemNow': 'अभी रिडीम करें',
  'confirmRedemption': 'रिडेम्पशन की पुष्टि करें',
  'redeemConfirmMessage':
      'क्या आप वाकई {points} पॉइंट्स के लिए {title} रिडीम करना चाहते हैं?',
  'confirm': 'पुष्टि करें',
  'successfullyRedeemed': '{title} सफलतापूर्वक रिडीम किया गया!',

  // Error Messages
  'loginFailed': 'लॉगिन विफल: {error}',
  'registrationFailed': 'पंजीकरण विफल: {error}',
  'errorOccurred': 'त्रुटि: {error}',
  'fillAllFields': 'कृपया सभी फ़ील्ड भरें',
};
