const Map<String, String> mr = {
  // General
  'appTitle': 'रायनो बाँड',
  'welcome': 'स्वागत आहे',
  'welcomeBack': 'पुन्हा स्वागत आहे',
  'signInToContinue': 'सुरू ठेवण्यासाठी साइन इन करा',
  'loading': 'लोड होत आहे...',

  // Auth & Profile
  'login': 'लॉगिन',
  'register': 'नोंदणी करा',
  'phoneNumber': 'फोन नंबर',
  'email': 'ईमेल',
  'password': 'पासवर्ड',
  'currentPassword': 'सध्याचा पासवर्ड',
  'newPassword': 'नवीन पासवर्ड',
  'confirmPassword': 'नवीन पासवर्ड पुष्टी करा',
  'fullName': 'पूर्ण नाव',
  'address': 'पत्ता',
  'pincode': 'पिनकोड',
  'state': 'राज्य',
  'enterOtp': 'ओटीपी प्रविष्ट करा',
  'sendOtp': 'ओटीपी पाठवा',
  'verifyOtp': 'ओटीपी तपासा',
  'otpSentSuccessfully': 'ओटीपी यशस्वीरित्या पाठवला गेला!',
  'pleaseEnterPhoneNumber': 'कृपया आपला फोन नंबर प्रविष्ट करा',
  'pleaseEnterOtp': 'कृपया ओटीपी प्रविष्ट करा',
  'invalidOtp': 'अमान्य ओटीपी',
  'loginSuccessful': 'लॉगिन यशस्वीरित्या झाले!',

  // Validation Messages
  'pleaseEnterName': 'कृपया आपले नाव प्रविष्ट करा',
  'pleaseEnterEmail': 'कृपया आपला ईमेल प्रविष्ट करा',
  'pleaseEnterValidEmail': 'कृपया वैध ईमेल प्रविष्ट करा',
  'pleaseEnterPhone': 'कृपया आपला फोन नंबर प्रविष्ट करा',
  'pleaseEnterPassword': 'कृपया आपला पासवर्ड प्रविष्ट करा',
  'pleaseEnterCurrentPassword': 'कृपया आपला सध्याचा पासवर्ड प्रविष्ट करा',
  'pleaseEnterNewPassword': 'कृपया नवीन पासवर्ड प्रविष्ट करा',
  'pleaseConfirmPassword': 'कृपया आपल्या नवीन पासवर्डची पुष्टी करा',
  'passwordsDoNotMatch': 'पासवर्ड जुळत नाहीत',
  'passwordMinLength': 'पासवर्ड किमान 6 अक्षरांचा असावा',
  'pincodeMustBe6Digits': 'पिनकोड 6 अंकी असावा',
  'phoneMustBe10Digits': 'फोन नंबर 10 अंकी असावा',
  'pleaseEnterAddress': 'कृपया आपला पत्ता प्रविष्ट करा',
  'pleaseEnterPincode': 'कृपया आपला पिनकोड प्रविष्ट करा',
  'pleaseEnterState': 'कृपया आपला राज्य प्रविष्ट करा',

  // Settings
  'settings': 'सेटिंग्ज',
  'profileSettings': 'प्रोफाइल सेटिंग्ज',
  'appSettings': 'अॅप सेटिंग्ज',
  'security': 'सुरक्षा',
  'changePassword': 'पासवर्ड बदला',
  'editProfile': 'प्रोफाइल संपादित करा',
  'darkMode': 'डार्क मोड',
  'pushNotifications': 'पुश नोटिफिकेशन्स',
  'notificationsSubtitle': 'रिवॉर्ड्स आणि अपडेट्सबद्दल नोटिफिकेशन्स मिळवा',
  'language': 'भाषा',
  'biometricAuth': 'बायोमेट्रिक प्रमाणीकरण',
  'biometricAuthSubtitle': 'लॉगिनसाठी फिंगरप्रिंट किंवा फेस आयडी वापरा',
  'privacyPolicy': 'गोपनीयता धोरण',
  'termsOfService': 'सेवेच्या अटी',
  'about': 'बद्दल',
  'appVersion': 'अॅप आवृत्ती',
  'checkForUpdates': 'अपडेट्स तपासा',
  'deleteAccount': 'खाते हटवा',
  'deleteAccountSubtitle': 'तुमचे खाते आणि सर्व डेटा कायमचा हटवा',
  'cancel': 'रद्द करा',
  'delete': 'हटवा',

  // Account
  'myAccount': 'माझे खाते',
  'saveProfile': 'प्रोफाइल जतन करा',
  'saveChanges': 'बदल जतन करा',
  'profileUpdated': 'प्रोफाइल यशस्वीरित्या अपडेट केले',
  'passwordChanged': 'पासवर्ड यशस्वीरित्या बदलला',

  // Rewards
  'points': 'पॉइंट्स',
  'pointsRequired': 'आवश्यक पॉइंट्स',
  'redeemNow': 'आता रिडीम करा',
  'confirmRedemption': 'रिडेम्पशनची पुष्टी करा',
  'redeemConfirmMessage':
      'तुम्हाला खरोखर {points} पॉइंट्ससाठी {title} रिडीम करायचे आहे का?',
  'confirm': 'पुष्टी करा',
  'successfullyRedeemed': '{title} यशस्वीरित्या रिडीम केले!',

  // Error Messages
  'loginFailed': 'लॉगिन अयशस्वी: {error}',
  'registrationFailed': 'नोंदणी अयशस्वी: {error}',
  'errorOccurred': 'त्रुटी: {error}',
  'fillAllFields': 'कृपया सर्व फील्ड भरा',
};
