const Map<String, String> pa = {
  // General
  'appTitle': 'ਰਾਈਨੋ ਬਾਂਡ',
  'welcome': 'ਜੀ ਆਇਆਂ ਨੂੰ',
  'welcomeBack': 'ਵਾਪਸ ਆਉਣ ਤੇ ਜੀ ਆਇਆਂ ਨੂੰ',
  'signInToContinue': 'ਜਾਰੀ ਰੱਖਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ',
  'loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',

  // Auth & Profile
  'login': 'ਲੌਗਿਨ',
  'register': 'ਰਜਿਸਟਰ',
  'phoneNumber': 'ਫ਼ੋਨ ਨੰਬਰ',
  'email': 'ਈਮੇਲ',
  'password': 'ਪਾਸਵਰਡ',
  'currentPassword': 'ਮੌਜੂਦਾ ਪਾਸਵਰਡ',
  'newPassword': 'ਨਵਾਂ ਪਾਸਵਰਡ',
  'confirmPassword': 'ਨਵੇਂ ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
  'fullName': 'ਪੂਰਾ ਨਾਮ',
  'address': 'ਪਤਾ',
  'pincode': 'ਪਿੰਨ ਕੋਡ',
  'state': 'ਰਾਜ',
  'enterOtp': 'ਓਟੀਪੀ ਦਾਖਲ ਕਰੋ',
  'sendOtp': 'ਓਟੀਪੀ ਭੇਜੋ',
  'verifyOtp': 'ਓਟੀਪੀ ਪੁਸ਼ਟੀ ਕਰੋ',
  'otpSentSuccessfully': 'ਓਟੀਪੀ ਸਫਲਤਾਪੂਰਵਕ ਭੇਜ ਦਿੱਤਾ ਗਿਆ!',
  'pleaseEnterPhoneNumber': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਫ਼ੋਨ ਨੰਬਰ ਦਾਖਲ ਕਰੋ',
  'pleaseEnterOtp': 'ਕਿਰਪਾ ਕਰਕੇ ਓਟੀਪੀ ਦਾਖਲ ਕਰੋ',
  'invalidOtp': 'ਗਲਤ ਓਟੀਪੀ',
  'loginSuccessful': 'ਲੌਗਿਨ ਸਫਲਤਾਪੂਰਵਕ ਹੋ ਗਿਆ!',

  // Validation Messages
  'pleaseEnterName': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਨਾਮ ਦਰਜ ਕਰੋ',
  'pleaseEnterEmail': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀ ਈਮੇਲ ਦਰਜ ਕਰੋ',
  'pleaseEnterValidEmail': 'ਕਿਰਪਾ ਕਰਕੇ ਵੈਧ ਈਮੇਲ ਦਰਜ ਕਰੋ',
  'pleaseEnterPhone': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਫ਼ੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ',
  'pleaseEnterPassword': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
  'pleaseEnterCurrentPassword': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਮੌਜੂਦਾ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
  'pleaseEnterNewPassword': 'ਕਿਰਪਾ ਕਰਕੇ ਨਵਾਂ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
  'pleaseConfirmPassword': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੇ ਨਵੇਂ ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
  'passwordsDoNotMatch': 'ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ',
  'passwordMinLength': 'ਪਾਸਵਰਡ ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰਾਂ ਦਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ',
  'pincodeMustBe6Digits': 'ਪਿੰਨ ਕੋਡ 6 ਅੰਕਾਂ ਦਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ',
  'phoneMustBe10Digits': 'ਫ਼ੋਨ ਨੰਬਰ 10 ਅੰਕਾਂ ਦਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ',
  'pleaseEnterAddress': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਪਤਾ ਦਰਜ ਕਰੋ',
  'pleaseEnterPincode': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਪਿੰਨ ਕੋਡ ਦਰਜ ਕਰੋ',
  'pleaseEnterState': 'ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਰਾਜ ਦਰਜ ਕਰੋ',

  // Settings
  'settings': 'ਸੈਟਿੰਗਾਂ',
  'profileSettings': 'ਪ੍ਰੋਫਾਈਲ ਸੈਟਿੰਗਾਂ',
  'appSettings': 'ਐਪ ਸੈਟਿੰਗਾਂ',
  'security': 'ਸੁਰੱਖਿਆ',
  'changePassword': 'ਪਾਸਵਰਡ ਬਦਲੋ',
  'editProfile': 'ਪ੍ਰੋਫਾਈਲ ਸੰਪਾਦਿਤ ਕਰੋ',
  'darkMode': 'ਡਾਰਕ ਮੋਡ',
  'pushNotifications': 'ਪੁਸ਼ ਨੋਟੀਫਿਕੇਸ਼ਨ',
  'notificationsSubtitle': 'ਰਿਵਾਰਡਾਂ ਅਤੇ ਅੱਪਡੇਟਾਂ ਬਾਰੇ ਨੋਟੀਫਿਕੇਸ਼ਨ ਪ੍ਰਾਪਤ ਕਰੋ',
  'language': 'ਭਾਸ਼ਾ',
  'biometricAuth': 'ਬਾਇਓਮੈਟ੍ਰਿਕ ਪ੍ਰਮਾਣੀਕਰਨ',
  'biometricAuthSubtitle': 'ਲੌਗਿਨ ਲਈ ਫਿੰਗਰਪ੍ਰਿੰਟ ਜਾਂ ਫੇਸ ਆਈਡੀ ਵਰਤੋ',
  'privacyPolicy': 'ਪਰਾਈਵੇਸੀ ਨੀਤੀ',
  'termsOfService': 'ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ',
  'about': 'ਬਾਰੇ',
  'appVersion': 'ਐਪ ਵਰਜਨ',
  'checkForUpdates': 'ਅੱਪਡੇਟਾਂ ਲਈ ਜਾਂਚ ਕਰੋ',
  'deleteAccount': 'ਖਾਤਾ ਮਿਟਾਓ',
  'deleteAccountSubtitle': 'ਆਪਣਾ ਖਾਤਾ ਅਤੇ ਸਾਰਾ ਡੇਟਾ ਸਥਾਈ ਤੌਰ ਤੇ ਮਿਟਾਓ',
  'cancel': 'ਰੱਦ ਕਰੋ',
  'delete': 'ਮਿਟਾਓ',

  // Account
  'myAccount': 'ਮੇਰਾ ਖਾਤਾ',
  'saveProfile': 'ਪ੍ਰੋਫਾਈਲ ਸਾਂਭ ਕੇ ਰੱਖੋ',
  'saveChanges': 'ਤਬਦੀਲੀਆਂ ਸਾਂਭ ਕੇ ਰੱਖੋ',
  'profileUpdated': 'ਪ੍ਰੋਫਾਈਲ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਕ',
};
